trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install dotnet 3.1 SDK'
  inputs:
    version: '3.1.x'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: 'Build the solution'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Run the tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Packing'
  inputs:
    command: 'pack'
    packagesToPack: '**/RestMockCore.csproj'
    versioningScheme: 'off'

- task: NuGetAuthenticate@0
  displayName: 'Authenticating Nuget'
  inputs:
    nuGetServiceConnections: 'Nuget rest-mock-core'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget rest-mock-core'
